services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  auth-server:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
        - SERVICE_NAME=auth-server
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    env_file:
      - .env.auth-server
    networks:
      - backend

  event-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=event-server
    ports:
      - "3002:3000"
    networks:
      - backend

  gateway-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gateway-server
    ports:
      - "3003:3000"
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
